/**
 * ERZEUGT von tools/verwaltung-suchbestand.mjs — NICHT von Hand aendern.
 *
 * Was die Suche der Verwaltung kennt: der sichtbare Text jedes Knopfes, jeder
 * Beschriftung und jeder Ueberschrift, samt der Seite, auf der er liegt.
 * Erhoben wird er aus den Seiten selbst, damit er nicht auseinanderlaeuft;
 * dass er es nicht tut, prueft tools/verwaltung-suche-vollstaendig.test.mjs.
 *
 * Erneuern:  node tools/verwaltung-suchbestand.mjs --schreiben
 */
import type { SuchEintrag } from './suche.filter'

export const SUCH_BESTAND: SuchEintrag[] = [
  { text: 'Übersicht', seite: 'Übersicht', weg: '/', bereich: 'Seite' },
  { text: 'Was da ist', seite: 'Übersicht', weg: '/', bereich: '' },
  { text: 'Was man sieht und hört', seite: 'Übersicht', weg: '/', bereich: '' },
  { text: 'Was die Box ist', seite: 'Übersicht', weg: '/', bereich: '' },
  { text: 'Wenn etwas klemmt', seite: 'Übersicht', weg: '/', bereich: '' },
  { text: 'Profile', seite: 'Profile', weg: '/kinderzeit', bereich: 'Seite' },
  { text: 'Wenn die Box eingeschaltet wird', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Name und Bild', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Name', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Name des Kindes', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Bild ändern', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'ohne', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Schloss', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Zahlen', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Zeichen', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Farben', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Muster', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Bilder', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Neues Passwort', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'mindestens 3 Zeichen', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Abnehmen', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Profile verwalten', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Neues Profil', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Gast', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Dauer', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'dauerhaft', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: '2 Stunden', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: '4 Stunden', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: '8 Stunden', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: '24 Stunden', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Medienliste übernehmen von', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'alles sichtbar', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Statistik — was gehört wurde', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Zeitraum', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'heute', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: '7 Tage', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: '30 Tage', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'ein Jahr', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'alle Profile', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Zurück zur Hausregel', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Eigene Regeln für', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Spielzeiten einschalten Kinderzeit', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Geburtstag', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Montag auf alle Wochentage übertragen', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Montag auf alle sieben Tage übertragen', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Für heute etwas dazugeben — an', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: '15 min', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: '30 min', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Heutigen Zähler zurücksetzen', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Schlummer-Timer', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Timer abbrechen', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Timer starten', seite: 'Profile', weg: '/kinderzeit', bereich: '' },
  { text: 'Medien', seite: 'Medien', weg: '/medien', bereich: 'Seite' },
  { text: 'überall suchen — Bibliothek sofort, Dienste und Archiv mit Enter', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Bibliothek', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Dienste', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Sender', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Regal', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Archiv', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Was aus den Quellen wird', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Doppelte zusammenfassen', seite: 'Medien', weg: '/medien', bereich: 'Was aus den Quellen wird' },
  { text: 'Ganze Diskografie', seite: 'Medien', weg: '/medien', bereich: 'Was aus den Quellen wird' },
  { text: 'Neu einlesen', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Suchen und aufnehmen', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Album, Interpret, Hörspiel …', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'Alben, Listen, Hörbücher', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'nur Alben', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'nur Listen', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'nur Hörbücher und Sendungen', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'einzelne Titel', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'Interpret — seine Alben', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'alle Dienste', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'nur Spotify', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'nur Jellyfin', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'nur ARD Sounds', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'Interpret', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'alle', seite: 'Medien', weg: '/medien', bereich: 'Suchen und aufnehmen' },
  { text: 'Eigene Liste', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Liste wählen', seite: 'Medien', weg: '/medien', bereich: 'Eigene Liste' },
  { text: '＋ neue Liste anlegen …', seite: 'Medien', weg: '/medien', bereich: 'Eigene Liste' },
  { text: 'Name der neuen Liste', seite: 'Medien', weg: '/medien', bereich: 'Eigene Liste' },
  { text: 'Anlegen', seite: 'Medien', weg: '/medien', bereich: 'Eigene Liste' },
  { text: 'Abbrechen', seite: 'Medien', weg: '/medien', bereich: 'Eigene Liste' },
  { text: 'Bei Spotify nicht mehr vorhanden', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'rückgängig', seite: 'Medien', weg: '/medien', bereich: 'Bei Spotify nicht mehr vorhanden' },
  { text: 'Aufnahmen', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Regale von ARD Sounds', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'neu laden', seite: 'Medien', weg: '/medien', bereich: 'Regale von ARD Sounds' },
  { text: 'im Regal suchen …', seite: 'Medien', weg: '/medien', bereich: 'Regale von ARD Sounds' },
  { text: 'Sammlungen von ARD Sounds', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'auch die übrigen ( insgesamt)', seite: 'Medien', weg: '/medien', bereich: 'Sammlungen von ARD Sounds' },
  { text: 'Radiosender von ARD Sounds', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'suchen', seite: 'Medien', weg: '/medien', bereich: 'Radiosender von ARD Sounds' },
  { text: 'z. B. Maus, WDR, Kultur', seite: 'Medien', weg: '/medien', bereich: 'Radiosender von ARD Sounds' },
  { text: 'Erweiterungen', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Internet Archive', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'z. B. Grimm, Rübezahl, Hörspiel', seite: 'Medien', weg: '/medien', bereich: 'Internet Archive' },
  { text: 'In der Bibliothek', seite: 'Medien', weg: '/medien', bereich: '' },
  { text: 'Schnellwahl', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'aufnehmen', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'abwählen', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'fertig', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'filtern nach Titel, Interpret, Dienst …', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'alle Kategorien', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'andere Dienste automatisch prüfen', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'ARD-Jingle überall überspringen', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'Jingle überspringen', seite: 'Medien', weg: '/medien', bereich: 'In der Bibliothek' },
  { text: 'Doppelte', seite: 'Doppelte', weg: '/verschmelzung', bereich: 'Seite', eltern: 'Medien' },
  { text: 'Der Schalter', seite: 'Doppelte', weg: '/verschmelzung', bereich: '', eltern: 'Medien' },
  { text: 'Erst hier aufräumen: derselbe Schlüssel steht zweimal', seite: 'Doppelte', weg: '/verschmelzung', bereich: '', eltern: 'Medien' },
  { text: 'Zusammengefasst', seite: 'Doppelte', weg: '/verschmelzung', bereich: '', eltern: 'Medien' },
  { text: 'Abgleichen', seite: 'Doppelte', weg: '/verschmelzung', bereich: '', eltern: 'Medien' },
  { text: 'Gefunden, aber nicht zusammengefasst', seite: 'Doppelte', weg: '/verschmelzung', bereich: '', eltern: 'Medien' },
  { text: 'Von Hand zusammenlegen', seite: 'Doppelte', weg: '/verschmelzung', bereich: '', eltern: 'Medien' },
  { text: 'erstes Werk', seite: 'Doppelte', weg: '/verschmelzung', bereich: 'Von Hand zusammenlegen', eltern: 'Medien' },
  { text: 'zweites Werk', seite: 'Doppelte', weg: '/verschmelzung', bereich: 'Von Hand zusammenlegen', eltern: 'Medien' },
  { text: 'Zusammenlegen', seite: 'Doppelte', weg: '/verschmelzung', bereich: 'Von Hand zusammenlegen', eltern: 'Medien' },
  { text: 'Von Hand getrennt', seite: 'Doppelte', weg: '/verschmelzung', bereich: '', eltern: 'Medien' },
  { text: 'wieder zulassen', seite: 'Doppelte', weg: '/verschmelzung', bereich: 'Von Hand getrennt', eltern: 'Medien' },
  { text: 'Interpreten', seite: 'Interpreten', weg: '/interpreten', bereich: 'Seite', eltern: 'Medien' },
  { text: 'Wie das mit „Ganze Diskografie“ zusammenhängt', seite: 'Interpreten', weg: '/interpreten', bereich: '', eltern: 'Medien' },
  { text: 'Aus deiner Bibliothek', seite: 'Interpreten', weg: '/interpreten', bereich: '', eltern: 'Medien' },
  { text: 'Nicht in der Reihe', seite: 'Interpreten', weg: '/interpreten', bereich: '', eltern: 'Medien' },
  { text: 'freischalten', seite: 'Interpreten', weg: '/interpreten', bereich: 'Nicht in der Reihe', eltern: 'Medien' },
  { text: 'bei Spotify suchen', seite: 'Interpreten', weg: '/interpreten', bereich: 'Nicht in der Reihe', eltern: 'Medien' },
  { text: 'zurück zur Automatik', seite: 'Interpreten', weg: '/interpreten', bereich: 'Nicht in der Reihe', eltern: 'Medien' },
  { text: 'In der Reihe', seite: 'Interpreten', weg: '/interpreten', bereich: '', eltern: 'Medien' },
  { text: 'festschreiben', seite: 'Interpreten', weg: '/interpreten', bereich: 'In der Reihe', eltern: 'Medien' },
  { text: 'Suchen und freischalten', seite: 'Interpreten', weg: '/interpreten', bereich: '', eltern: 'Medien' },
  { text: 'Name des Interpreten', seite: 'Interpreten', weg: '/interpreten', bereich: 'Suchen und freischalten', eltern: 'Medien' },
  { text: 'doch nicht zuordnen', seite: 'Interpreten', weg: '/interpreten', bereich: 'Suchen und freischalten', eltern: 'Medien' },
  { text: 'Freigeschaltet', seite: 'Interpreten', weg: '/interpreten', bereich: '', eltern: 'Medien' },
  { text: 'Abgelehnt', seite: 'Interpreten', weg: '/interpreten', bereich: '', eltern: 'Medien' },
  { text: 'Alles zurücknehmen', seite: 'Interpreten', weg: '/interpreten', bereich: '', eltern: 'Medien' },
  { text: 'Streaming-Dienste', seite: 'Streaming-Dienste', weg: '/streaming', bereich: 'Seite' },
  { text: 'Welcher Client spielt', seite: 'Streaming-Dienste', weg: '/streaming', bereich: '' },
  { text: 'Die Ströme', seite: 'Streaming-Dienste', weg: '/streaming', bereich: '' },
  { text: 'Einstellungen für', seite: 'Streaming-Dienste', weg: '/streaming', bereich: '' },
  { text: 'Verwerfen', seite: 'Streaming-Dienste', weg: '/streaming', bereich: '' },
  { text: 'Aufzeichnen', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: 'Seite' },
  { text: 'Nachtmodus', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: '' },
  { text: 'Alben komplett aufnehmen', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: '' },
  { text: 'Suchen: Titel, Album oder Interpret', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: '' },
  { text: 'Nimmt gerade auf', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: '' },
  { text: 'Warteschlange', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: '' },
  { text: 'Liegen mit Fehler', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: '' },
  { text: 'Aufgezeichnet', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: '' },
  { text: 'Alle einreihen', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: 'Aufgezeichnet' },
  { text: 'Alle Alben zeigen', seite: 'Aufzeichnen', weg: '/aufzeichnen', bereich: 'Aufgezeichnet' },
  { text: 'Darstellung', seite: 'Darstellung', weg: '/darstellung', bereich: 'Seite' },
  { text: '? Erklärungen', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Auswahl aufheben', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Größe', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Länge', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Standard', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Höhe', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Abstand der Alben', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'normal', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Länge der Zeile', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: '„endet um …"', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Abstand zum Bild', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Sichtbar', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Aus der Konfiguration der Box', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Helligkeit des Bildschirms', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Helligkeit', seite: 'Darstellung', weg: '/darstellung', bereich: 'Helligkeit des Bildschirms' },
  { text: 'Vorschau', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Startseite', seite: 'Darstellung', weg: '/darstellung', bereich: 'Vorschau' },
  { text: 'Player', seite: 'Darstellung', weg: '/darstellung', bereich: 'Vorschau' },
  { text: 'Neu laden', seite: 'Darstellung', weg: '/darstellung', bereich: 'Vorschau' },
  { text: 'Themen', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Thema', seite: 'Darstellung', weg: '/darstellung', bereich: 'Themen' },
  { text: 'Name', seite: 'Darstellung', weg: '/darstellung', bereich: 'Themen' },
  { text: 'Speichern', seite: 'Darstellung', weg: '/darstellung', bereich: 'Themen' },
  { text: 'Abgelegt', seite: 'Darstellung', weg: '/darstellung', bereich: 'Themen' },
  { text: 'Aus Datei', seite: 'Darstellung', weg: '/darstellung', bereich: 'Themen' },
  { text: '„ " ersetzen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Themen' },
  { text: 'Abbrechen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Themen' },
  { text: 'Verhalten', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Album-Tipp', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Titelliste', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'spielt sofort', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Titelkarte', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Cover-Reihen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'wie früher', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Vollbild-Blättern', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Beim Verlassen der Titel', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'spielt weiter', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'stoppt', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Startkategorie', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'keine', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Kategorienleiste', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Liste', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'ein Knopf', seite: 'Darstellung', weg: '/darstellung', bereich: 'Verhalten' },
  { text: 'Gesten', seite: 'Darstellung', weg: '/darstellung', bereich: '' },
  { text: 'Zwei Finger', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Über den Player streichen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'kommt zurück nach', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Vom Rand', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Randstreifen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'zurück', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Mini-Player', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Fortschrittsstreifen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Wellen im Player', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Wellen in Regenbogenfarben', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Punkt auf dem Balken', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'kein Punkt', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Form', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: '„endet um"', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Platz beim Blättern', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Spielt-Marke', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Bühne über den Tasten', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Höhe der Bühne', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Tempo', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Glasflächen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Kissen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'großer Player', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Akzent des Players', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Zeilen im Kissen', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Titel', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Album', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Namen unter den Alben', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Abstand Name↔Bild', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Albumkacheln', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'rund', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'abgerundet', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'eckig', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Umrandung', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Mitte der Kopfzeile', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Tipp sagt die Zeit', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Restzeit des Stücks', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Titel-Rest', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Schlummer-Rest', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Standanzeigen rechts', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Akku', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Lautstärke', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Internet', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'WLAN', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Bluetooth-Ladestand', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Prozent', seite: 'Darstellung', weg: '/darstellung', bereich: 'Gesten' },
  { text: 'Vorlesen', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Seite' },
  { text: 'Wann wird vorgelesen?', seite: 'Vorlesen', weg: '/vorlesen', bereich: '' },
  { text: 'Stimme', seite: 'Vorlesen', weg: '/vorlesen', bereich: '' },
  { text: 'wirklich?', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Stimme' },
  { text: 'entfernen', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Stimme' },
  { text: 'Tempo', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Stimme' },
  { text: 'Interpret mitsprechen', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Stimme' },
  { text: 'Silben ausprobieren', seite: 'Vorlesen', weg: '/vorlesen', bereich: '' },
  { text: 'Titel eingeben, z. B. Kinderlieder', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Silben ausprobieren' },
  { text: '▶ anhören', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Silben ausprobieren' },
  { text: 'Weitere Stimmen laden', seite: 'Vorlesen', weg: '/vorlesen', bereich: '' },
  { text: 'auswählen', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Weitere Stimmen laden' },
  { text: 'oder einen Piper-Namen, z. B. da_DK-talesyntese-medium', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Weitere Stimmen laden' },
  { text: 'laden', seite: 'Vorlesen', weg: '/vorlesen', bereich: 'Weitere Stimmen laden' },
  { text: 'Videos', seite: 'Videos', weg: '/videos', bereich: 'Seite' },
  { text: 'Für wen', seite: 'Videos', weg: '/videos', bereich: '' },
  { text: 'Suchen und freigeben', seite: 'Videos', weg: '/videos', bereich: '' },
  { text: 'Suchen', seite: 'Videos', weg: '/videos', bereich: 'Suchen und freigeben' },
  { text: 'Teilen…', seite: 'Videos', weg: '/videos', bereich: 'Suchen und freigeben' },
  { text: '„ “ teilen', seite: 'Videos', weg: '/videos', bereich: '' },
  { text: 'Hier schneiden', seite: 'Videos', weg: '/videos', bereich: '„ “ teilen' },
  { text: 'Letzten Marker weg', seite: 'Videos', weg: '/videos', bereich: '„ “ teilen' },
  { text: 'Ansehen', seite: 'Videos', weg: '/videos', bereich: '„ “ teilen' },
  { text: 'Alle Teile × freigeben', seite: 'Videos', weg: '/videos', bereich: '„ “ teilen' },
  { text: 'Schließen', seite: 'Videos', weg: '/videos', bereich: '„ “ teilen' },
  { text: 'Freigegeben für', seite: 'Videos', weg: '/videos', bereich: '' },
  { text: 'Spiele', seite: 'Spiele', weg: '/spiele', bereich: 'Seite' },
  { text: 'Darf gespielt werden?', seite: 'Spiele', weg: '/spiele', bereich: '' },
  { text: 'Welche Spiele?', seite: 'Spiele', weg: '/spiele', bereich: '' },
  { text: 'Spricht die Box beim Spielen?', seite: 'Spiele', weg: '/spiele', bereich: '' },
  { text: 'Die Schublade am Schirm', seite: 'Spiele', weg: '/spiele', bereich: '' },
  { text: 'Konfiguration', seite: 'Konfiguration', weg: '/konfiguration', bereich: 'Seite' },
  { text: 'Passwort der Verwaltung', seite: 'Konfiguration', weg: '/konfiguration', bereich: '' },
  { text: 'Neues Passwort', seite: 'Konfiguration', weg: '/konfiguration', bereich: 'Passwort der Verwaltung' },
  { text: 'PIN vor den Einstellungen der Box', seite: 'Konfiguration', weg: '/konfiguration', bereich: '' },
  { text: 'Neue PIN (4–8 Ziffern)', seite: 'Konfiguration', weg: '/konfiguration', bereich: 'PIN vor den Einstellungen der Box' },
  { text: 'Verwerfen', seite: 'Konfiguration', weg: '/konfiguration', bereich: 'PIN vor den Einstellungen der Box' },
  { text: 'Netzwerk', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Seite' },
  { text: 'WLAN-Adapter', seite: 'Netzwerk', weg: '/netzwerk', bereich: '' },
  { text: 'Eingebaut', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'WLAN-Adapter' },
  { text: 'WLAN-Stick', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'WLAN-Adapter' },
  { text: 'Funk an und aus', seite: 'Netzwerk', weg: '/netzwerk', bereich: '' },
  { text: 'Einschalten', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Funk an und aus' },
  { text: 'Ausschalten', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Funk an und aus' },
  { text: 'Beenden', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Funk an und aus' },
  { text: 'Ja, abschalten', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Funk an und aus' },
  { text: 'Abbrechen', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Funk an und aus' },
  { text: 'Anschlüsse', seite: 'Netzwerk', weg: '/netzwerk', bereich: '' },
  { text: 'Gespeicherte Netze', seite: 'Netzwerk', weg: '/netzwerk', bereich: '' },
  { text: 'Verbinden', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Gespeicherte Netze' },
  { text: 'Vergessen', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Gespeicherte Netze' },
  { text: 'Ja, vergessen', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'Gespeicherte Netze' },
  { text: 'WLAN einrichten', seite: 'Netzwerk', weg: '/netzwerk', bereich: '' },
  { text: 'WPS-Knopf', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'WLAN einrichten' },
  { text: 'Netzwerkname (SSID)', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'WLAN einrichten' },
  { text: 'Passwort (leer lassen für ein offenes Netz)', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'WLAN einrichten' },
  { text: 'Verbindung bestätigen', seite: 'Netzwerk', weg: '/netzwerk', bereich: 'WLAN einrichten' },
  { text: 'VPN', seite: 'VPN', weg: '/vpn', bereich: 'Seite' },
  { text: 'Das Werkzeug fehlt noch', seite: 'VPN', weg: '/vpn', bereich: '' },
  { text: 'Heimweg', seite: 'VPN', weg: '/vpn', bereich: '' },
  { text: 'Läuft gerade', seite: 'VPN', weg: '/vpn', bereich: 'Heimweg' },
  { text: 'Startet mit der Box', seite: 'VPN', weg: '/vpn', bereich: 'Heimweg' },
  { text: 'Verbindung entfernen', seite: 'VPN', weg: '/vpn', bereich: 'Heimweg' },
  { text: 'Ja, entfernen', seite: 'VPN', weg: '/vpn', bereich: 'Heimweg' },
  { text: 'Abbrechen', seite: 'VPN', weg: '/vpn', bereich: 'Heimweg' },
  { text: 'Einrichten — die Datei entsteht am Router', seite: 'VPN', weg: '/vpn', bereich: '' },
  { text: '[Interface]&#10;PrivateKey = …&#10;Address = …&#10;&#10;[Peer]&#10;PublicKey = …&#10;Endpoint = …', seite: 'VPN', weg: '/vpn', bereich: 'Einrichten — die Datei entsteht am Router' },
  { text: 'Netzlaufwerk', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Seite' },
  { text: 'Diesem Zertifikat vertrauen', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: '' },
  { text: 'Abbrechen', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: '' },
  { text: 'Das Werkzeug fehlt noch', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: '' },
  { text: 'Freigabe eintragen', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: '' },
  { text: 'WebDAV', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'Adresse der Freigabe', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'https://nas.fritz.box/remote.php/dav/files/achim/MuPiBox', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'Adresse des NAS', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'Freigabe', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'mupibox', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'Anmeldename', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'Passwort', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'Unterordner (kann leer bleiben)', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'Einhängepunkt auf der Box', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Freigabe eintragen' },
  { text: 'Eingetragene Freigabe', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: '' },
  { text: 'Bei Bedarf einhängen', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Eingetragene Freigabe' },
  { text: 'Hängt gerade', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Eingetragene Freigabe' },
  { text: 'Sicherungen dorthin spiegeln', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Eingetragene Freigabe' },
  { text: 'Freigabe entfernen', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Eingetragene Freigabe' },
  { text: 'Ja, entfernen', seite: 'Netzlaufwerk', weg: '/netzlaufwerk', bereich: 'Eingetragene Freigabe' },
  { text: 'Nachrichten', seite: 'Nachrichten', weg: '/nachrichten', bereich: 'Seite' },
  { text: 'Die drei Wege', seite: 'Nachrichten', weg: '/nachrichten', bereich: '' },
  { text: 'Wer der Box schreiben darf', seite: 'Nachrichten', weg: '/nachrichten', bereich: '' },
  { text: 'Entfernen', seite: 'Nachrichten', weg: '/nachrichten', bereich: 'Wer der Box schreiben darf' },
  { text: 'Mama', seite: 'Nachrichten', weg: '/nachrichten', bereich: 'Wer der Box schreiben darf' },
  { text: 'Eintragen', seite: 'Nachrichten', weg: '/nachrichten', bereich: 'Wer der Box schreiben darf' },
  { text: 'Vorlesen — je Kind', seite: 'Nachrichten', weg: '/nachrichten', bereich: '' },
  { text: 'Wie die Box', seite: 'Nachrichten', weg: '/nachrichten', bereich: 'Vorlesen — je Kind' },
  { text: 'Was angekommen ist', seite: 'Nachrichten', weg: '/nachrichten', bereich: '' },
  { text: 'Alle löschen', seite: 'Nachrichten', weg: '/nachrichten', bereich: 'Was angekommen ist' },
  { text: 'Bluetooth', seite: 'Bluetooth', weg: '/bluetooth', bereich: 'Seite' },
  { text: 'namenlose Geräte einblenden', seite: 'Bluetooth', weg: '/bluetooth', bereich: '' },
  { text: 'Adapter', seite: 'Bluetooth', weg: '/bluetooth', bereich: '' },
  { text: 'Trennen', seite: 'Bluetooth', weg: '/bluetooth', bereich: '' },
  { text: 'Verbinden', seite: 'Bluetooth', weg: '/bluetooth', bereich: '' },
  { text: 'Entfernen', seite: 'Bluetooth', weg: '/bluetooth', bereich: '' },
  { text: 'Tonausgabe', seite: 'Bluetooth', weg: '/bluetooth', bereich: '' },
  { text: 'Ton', seite: 'Ton', weg: '/ton', bereich: 'Seite' },
  { text: 'Ausgaben', seite: 'Ton', weg: '/ton', bereich: '' },
  { text: 'Wie laut — je Quelle', seite: 'Ton', weg: '/ton', bereich: '' },
  { text: 'Klang (Equalizer)', seite: 'Ton', weg: '/ton', bereich: '' },
  { text: 'Equalizer verwenden', seite: 'Ton', weg: '/ton', bereich: 'Klang (Equalizer)' },
  { text: 'Klangwerk (Ton-Plugins)', seite: 'Ton', weg: '/ton', bereich: '' },
  { text: 'Grundeinstellungen', seite: 'Ton', weg: '/ton', bereich: '' },
  { text: '▶ Probehören', seite: 'Ton', weg: '/ton', bereich: 'Grundeinstellungen' },
  { text: 'Verwerfen', seite: 'Ton', weg: '/ton', bereich: 'Grundeinstellungen' },
  { text: 'MuPiHAT', seite: 'MuPiHAT', weg: '/mupihat', bereich: 'Seite' },
  { text: 'Ladestand', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Spannung (gemessen)', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Temperatur', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Lade- und Entladekurve', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Batterie', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Verbauter Pack', seite: 'MuPiHAT', weg: '/mupihat', bereich: 'Batterie' },
  { text: 'laut Aufkleber', seite: 'MuPiHAT', weg: '/mupihat', bereich: 'Batterie' },
  { text: 'Was die Box über den Pack gelernt hat', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Diagnose', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Platinenstand', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Mein Platinenstand', seite: 'MuPiHAT', weg: '/mupihat', bereich: 'Platinenstand' },
  { text: 'nicht eingetragen', seite: 'MuPiHAT', weg: '/mupihat', bereich: 'Platinenstand' },
  { text: 'Protokoll', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: '5 Minuten', seite: 'MuPiHAT', weg: '/mupihat', bereich: 'Protokoll' },
  { text: 'Verwerfen', seite: 'MuPiHAT', weg: '/mupihat', bereich: 'Protokoll' },
  { text: 'Letzte Phasen', seite: 'MuPiHAT', weg: '/mupihat', bereich: '' },
  { text: 'Plugins', seite: 'Plugins', weg: '/plugins', bereich: 'Seite' },
  { text: 'Nicht geladen', seite: 'Plugins', weg: '/plugins', bereich: '' },
  { text: 'Systemdienste', seite: 'Systemdienste', weg: '/dienste', bereich: 'Seite' },
  { text: 'Vom Start nehmen…', seite: 'Systemdienste', weg: '/dienste', bereich: '' },
  { text: 'Anhalten', seite: 'Systemdienste', weg: '/dienste', bereich: '' },
  { text: 'Neu starten', seite: 'Systemdienste', weg: '/dienste', bereich: '' },
  { text: 'Starten', seite: 'Systemdienste', weg: '/dienste', bereich: '' },
  { text: 'Kein Weg zurück — an der Box selbst', seite: 'Systemdienste', weg: '/dienste', bereich: '' },
  { text: 'Doch nicht', seite: 'Systemdienste', weg: '/dienste', bereich: 'Kein Weg zurück — an der Box selbst' },
  { text: 'Trotzdem vom Start nehmen', seite: 'Systemdienste', weg: '/dienste', bereich: 'Kein Weg zurück — an der Box selbst' },
  { text: 'Abgelöst', seite: 'Systemdienste', weg: '/dienste', bereich: '' },
  { text: 'Trotzdem starten', seite: 'Systemdienste', weg: '/dienste', bereich: 'Abgelöst' },
  { text: 'System', seite: 'System', weg: '/system', bereich: 'Seite' },
  { text: 'Verlauf', seite: 'System', weg: '/system', bereich: '' },
  { text: 'Wartung', seite: 'System', weg: '/system', bereich: '' },
  { text: 'Oberfläche neu laden', seite: 'System', weg: '/system', bereich: 'Wartung' },
  { text: 'Systemeinstellungen', seite: 'System', weg: '/system', bereich: '' },
  { text: 'wählen', seite: 'System', weg: '/system', bereich: 'Systemeinstellungen' },
  { text: 'Box aus- und einschalten', seite: 'System', weg: '/system', bereich: '' },
  { text: 'Abbrechen', seite: 'System', weg: '/system', bereich: 'Box aus- und einschalten' },
  { text: 'Leistung', seite: 'Leistung', weg: '/leistung', bereich: 'Seite' },
  { text: 'Live ( s)', seite: 'Leistung', weg: '/leistung', bereich: '' },
  { text: 'Speicher je Posten', seite: 'Leistung', weg: '/leistung', bereich: '' },
  { text: 'Der Start', seite: 'Leistung', weg: '/leistung', bereich: '' },
  { text: 'Zeitachse des Starts', seite: 'Leistung', weg: '/leistung', bereich: '' },
  { text: 'Verlauf', seite: 'Leistung', weg: '/leistung', bereich: '' },
  { text: 'Protokolle', seite: 'Protokolle', weg: '/protokolle', bereich: 'Seite' },
  { text: 'Nur Fehler und Warnungen', seite: 'Protokolle', weg: '/protokolle', bereich: '' },
  { text: 'Aktualisierung', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: 'Seite' },
  { text: 'Wartungsmodus', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: '' },
  { text: 'Wartung beenden', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: 'Wartungsmodus' },
  { text: 'Wartungsmodus einschalten', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: 'Wartungsmodus' },
  { text: 'Was hier läuft', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: '' },
  { text: 'Was angeboten wird', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: '' },
  { text: 'Einspielen', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: '' },
  { text: 'Trotzdem einspielen', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: 'Einspielen' },
  { text: 'Erneut nachsehen', seite: 'Aktualisierung', weg: '/aktualisierung', bereich: 'Einspielen' },
  { text: 'Sicherung', seite: 'Sicherung', weg: '/sicherung', bereich: 'Seite' },
  { text: 'Das Sicherungswerkzeug fehlt auf dieser Box', seite: 'Sicherung', weg: '/sicherung', bereich: '' },
  { text: 'Die Anmeldung dieser Verwaltung ist ausgeschaltet', seite: 'Sicherung', weg: '/sicherung', bereich: '' },
  { text: 'Jetzt sichern und herunterladen', seite: 'Sicherung', weg: '/sicherung', bereich: '' },
  { text: 'Zugangsdaten mitnehmen (Spotify, WLAN, Verwaltungspasswort) — verschlüsselt', seite: 'Sicherung', weg: '/sicherung', bereich: 'Jetzt sichern und herunterladen' },
  { text: 'Passwort für die Zugangsdaten', seite: 'Sicherung', weg: '/sicherung', bereich: 'Jetzt sichern und herunterladen' },
  { text: 'Stände auf der Box', seite: 'Sicherung', weg: '/sicherung', bereich: '' },
  { text: 'Herunterladen', seite: 'Sicherung', weg: '/sicherung', bereich: 'Stände auf der Box' },
  { text: 'Eine Sicherung zurückspielen', seite: 'Sicherung', weg: '/sicherung', bereich: '' },
  { text: 'Das würde passieren', seite: 'Sicherung', weg: '/sicherung', bereich: '' },
  { text: 'Die verschlüsselten Zugangsdaten mit einspielen', seite: 'Sicherung', weg: '/sicherung', bereich: 'Das würde passieren' },
  { text: 'Passwort dieses Standes', seite: 'Sicherung', weg: '/sicherung', bereich: 'Das würde passieren' },
  { text: 'Abbrechen', seite: 'Sicherung', weg: '/sicherung', bereich: 'Das würde passieren' },
  { text: 'Zurückgespielt', seite: 'Sicherung', weg: '/sicherung', bereich: '' },
]
